language: node_js
node_js: 
  - "10.15.1"

install:
  - npm install

before_script:
  - cd foundations-zh
  - npm install -g tslint jest typescript

script:
  - npm run lint

test:
  - npm run test

branches:
  only:
    - master