language: node_js
node_js: 
  - "10.15.1"

install:
  - npm install

before_script:
  - npm install -g tslint
  - npm install -g jest

script:
  - cd foundations-zh && npm run lint

test:
  - npm run test

branches:
  only:
    - master